services:
  - type: web
    name: expense-tracker-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 10000
